#!/usr/bin/env bash
#
# ClawbotOS MOTD header
# Based on YumiOS/MainsailOS MOTD
#
# This file is licensed under the terms of the GNU General Public
# License version 2.

# shellcheck enable=require-variable-braces

# shellcheck disable=SC1091
[[ -f /etc/armbian-release ]] && . /etc/armbian-release

if [[ -f /etc/armbian-distribution-status ]]; then
    . /etc/armbian-distribution-status
    [[ -f /etc/lsb-release ]] && DISTRIBUTION_CODENAME=$(grep CODENAME /etc/lsb-release | cut -d"=" -f2)
    [[ -z "${DISTRIBUTION_CODENAME}" && -f /etc/os-release ]] && DISTRIBUTION_CODENAME=$(grep VERSION_CODENAME /etc/os-release | cut -d"=" -f2)
    [[ -z "${DISTRIBUTION_CODENAME}" && -x /usr/bin/lsb_release ]] && DISTRIBUTION_CODENAME=$(/usr/bin/lsb_release -c | cut -d":" -f2 | tr -d "\t")
fi
[[ -f /etc/default/armbian-motd ]] && . /etc/default/armbian-motd

for f in ${MOTD_DISABLE}; do
    [[ "${f}" == "${THIS_SCRIPT}" ]] && exit 0
done

KERNELID=$(uname -r)

echo -e "\e[36m$(toilet -f big ClawbotOS 2>/dev/null || echo 'ClawbotOS')\e[0m"
if [[ -f /etc/clawbotos-release ]]; then
    echo -e "Version $(cut -d ' ' -f3 /etc/clawbotos-release), based on \
\e[34mArmbian ${VERSION/-trunk/} ${DISTRIBUTION_CODENAME^}\e[0m"
fi
echo -e "Running on \e[34m${BOARD_NAME}\e[0m with \e[34mLinux ${KERNELID}\e[0m\n"
echo -e "  Web Dashboard:  \e[32mhttp://clawbot.local\e[0m"
echo -e "  PicoClaw API:   \e[32mhttp://clawbot.local:8080\e[0m"
echo -e ""
