#!/usr/bin/env bash
#### PicoClaw - Lightweight AI Agent by Sipeed
####
#### https://github.com/sipeed/picoclaw
#### This File is distributed under GPLv3
####

# shellcheck disable=all

[[ -n "$PICOCLAW_REPO" ]] || PICOCLAW_REPO="https://github.com/Yumi-Lab/picoclaw.git"
[[ -n "$PICOCLAW_REPO_BRANCH" ]] || PICOCLAW_REPO_BRANCH="main"

# PicoClaw version
[[ -n "$PICOCLAW_VERSION" ]] || PICOCLAW_VERSION="v0.1.2"
# Architecture for precompiled binary download (armv6 is compatible with ARMv7/H3)
[[ -n "$PICOCLAW_ARCH" ]] || PICOCLAW_ARCH="Linux_armv6"
# Download URL pattern for releases (tar.gz format)
[[ -n "$PICOCLAW_RELEASE_URL" ]] || PICOCLAW_RELEASE_URL="https://github.com/Yumi-Lab/picoclaw/releases/download/${PICOCLAW_VERSION}"
# Tarball filename
[[ -n "$PICOCLAW_TARBALL" ]] || PICOCLAW_TARBALL="picoclaw_${PICOCLAW_ARCH}.tar.gz"

# Go version for building from source (Bookworm only ships 1.19, too old)
[[ -n "$PICOCLAW_GO_VERSION" ]] || PICOCLAW_GO_VERSION="1.23.6"

# Gateway port
[[ -n "$PICOCLAW_PORT" ]] || PICOCLAW_PORT="8080"

# Dependencies
[[ -n "$PICOCLAW_DEPS" ]] || PICOCLAW_DEPS="git curl ca-certificates"
