#!/usr/bin/env bash
#### Open WebUI install module
####
#### https://github.com/open-webui/open-webui
#### This File is distributed under GPLv3
####

# shellcheck enable=require-variable-braces
set -Ee

# shellcheck disable=SC1091
source /common.sh
install_cleanup_trap

echo_green "Installing Open WebUI ..."

## Step 1: Install system dependencies
apt-get update --allow-releaseinfo-change
# shellcheck disable=SC2086
check_install_pkgs ${OPENWEBUI_DEPS}
## END Step 1

## Step 2: Create Python virtual environment
echo_green "Creating Python virtual environment ..."
pushd "/home/${BASE_USER}" &> /dev/null || exit 1
sudo -u "${BASE_USER}" python3 -m venv "/home/${BASE_USER}/open-webui-venv"
## END Step 2

## Step 3: Install Open WebUI via pip in venv
echo_green "Installing Open WebUI via pip (this may take a while) ..."
sudo -u "${BASE_USER}" "/home/${BASE_USER}/open-webui-venv/bin/pip" install --upgrade pip
sudo -u "${BASE_USER}" "/home/${BASE_USER}/open-webui-venv/bin/pip" install open-webui
## END Step 3

## Step 4: Create data directory
mkdir -p "/home/${BASE_USER}/open-webui-data"
chown -R "${BASE_USER}:${BASE_USER}" "/home/${BASE_USER}/open-webui-data"
## END Step 4

## Step 5: Install systemd service
echo_green "Installing Open WebUI systemd service ..."
unpack /filesystem/root /
## END Step 5

## Step 6: Enable service
echo_green "Enabling open-webui.service ..."
systemctl_if_exists enable open-webui.service
## END Step 6

popd &> /dev/null || exit 1

echo_green "Installing Open WebUI ... DONE!"
