#!/usr/bin/env bash
#### ClawbotOS network configurator for armbian images
####
#### Based on work of Stephan Wendel aka KwadFan
#### Modified for ClawbotOS by Yumi Lab
####
#### This File is distributed under GPLv3
####

# shellcheck enable=require-variable-braces

# Source error handling, leave this in place
set -Ee

# Source CustomPIOS common.sh
# shellcheck disable=SC1091
source /common.sh
install_cleanup_trap


## Step 1: Install files
unpack filesystem/root / root
## END

## Step 1.1: Install Dependencies
# shellcheck disable=SC2086
check_install_pkgs ${ARMBIAN_NET_DEPS}

## Step 2: remove original template
if [[ -f "${ARMBIAN_NET_FIRSTRUN_FILE}" ]]; then
    sudo rm -rf "${ARMBIAN_NET_FIRSTRUN_FILE}"
fi
## END

## Step 3: Disable first run service
systemctl_if_exists disable armbian-firstrun-config.service
## END

## Step 4: Copy original script to /usr/local/bin/network-configurator
if [[ -f "${ARMBIAN_NET_FIRSTRUN_SCRIPT}" ]]; then
    sudo cp -p "${ARMBIAN_NET_FIRSTRUN_SCRIPT}" "${ARMBIAN_NET_NC_PATH}"
fi
## END

## Step 5: patch /usr/local/bin/network-configurator
if [[ -f "${ARMBIAN_NET_NC_PATH}" ]]; then
    ### Substep 1: replace any armbian_first_run.txt with network_config.txt
    sed -i 's|armbian_first_run.txt|network_config.txt|g' "${ARMBIAN_NET_NC_PATH}"
    ### Substep 2: replace any FR* Variable name with NC*
    sed -i 's|FR|NC|g' "${ARMBIAN_NET_NC_PATH}"
    ### Substep 3: Rename function
    sed -i 's|do_firstrun_automated_user_configuration|do_network_configuration|g' "${ARMBIAN_NET_NC_PATH}"
    ### Substep 4: Add a patch note
    sed -i '8 i \\n\# This is a patched version of armbian-firstrun-config for ClawbotOS' "${ARMBIAN_NET_NC_PATH}"
    sed -i '10 i # Original located at /usr/lib/armbian/armbian-firstrun-config' "${ARMBIAN_NET_NC_PATH}"
    sed -i '11 i # Changes made by https:\/\/github.com/Yumi-Lab' "${ARMBIAN_NET_NC_PATH}"
fi
## END

## Step 6: Enable systemd service
systemctl_if_exists enable network-configurator.service
## END

## Step 7: Install and enable wifi-watchdog
chmod +x /usr/local/bin/wifi-watchdog
systemctl_if_exists enable wifi-watchdog.timer
## END
