#!/usr/bin/env bash
#### ClawbotOS Telegram Bot module
####
#### Written by Yumi Lab
#### This File is distributed under GPLv3
####

# shellcheck disable=all

[[ -n "$TELEGRAM_DEPS" ]] || TELEGRAM_DEPS="python3-pip python3-venv"
